### ISSUE TITLE
ESP32 I2C communication ignores delay between endTransmission and requestFrom

### ISSUE THREAD

**Issue by fernanpardo** [devxplained/HTU21D-Sensor-Library#4]
I tried your HTU21D for both ESP8266 and ESP32. For ESP8266 worked fine but it failed for ESP32. I compared your code to that of Adafruit and I found that you use ".endTransmission(false);" instead of default ".endTransmission();". Probable the "false" option is correct, but without the false parameter seems to be more compatible, in fact, the Adafruit version does not use that option.
I still prefer your version than Adafruit's because yours seems to be more robust.

**Comment by devxplained** [comment]
I cannot reproduce this issue with the latest Arduino core for the ESP32 (tested with 2.0.4). The boolean flag was added in a later version of the Arduino specification. It seems to me, that you are using a very old or non-standard version of the Arduino ESP32 support library. 

Can you try to update/reinstall it according to the official manual?
See: [https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html)
If it still doesn't work, please supply the exact version of your Arduino IDE and the ESP32 board package.

**Comment by fernanpardo** [comment]
I use Arduino framework on PlatformIO and Sparkfun ESP32 Thing. First I was using a very old Aduino/Espressif platform and the board kept on reseting when reading the sensor. With the current 7 days old 5.1.1 framework, it does not reset itself, but  it does not read the sensor either. May be it is something related to the board I'm using, though it perfectly works if I remove the "false" flag.

By the way, my HTU21D temperature readings are about 1 ºC higher than those obtained from a BME280. I guess it is not related to this issue, but it is strange.

**Comment by devxplained** [comment]
I have no issues of compiling for the ESP32 with version 5.1.1. However, I can confirm that it does not work with the ESP32 currently. The reason are a series of nasty bugs in the ESP32 SDK. I need to try around a bit what is the best way to solve this. Using false will change the communication behavior and send a stop bit. I would like to keep the communication like it is recommended in the sensors datasheet. However, it might take a bit till there is a solution. So for you, it is probably best to stick to using true instead of false for the while.

Regarding the temperature issue it's difficult to know the exact reason, according to the specs the difference should be below 0.9 °C. The temperature formula for the HTU21D is correct. So this should be indeed unrelated. Might be sensor placement.

**Comment by devxplained** [comment]
It seems that the i2c communication  on all ESP32 chips is handled by a dedicated hardware FSM. There is no support for delays in the communication. All commands are put into a queue and then executed. This means the recommended communication pattern for the HTU21D is not implementable for the ESP32.

I will extend the library with a workaround that uses two separate calls for triggering the measurement and reading the result by using `endTransmission(true)` which was what worked for you.

**Comment by devxplained** [comment]
I submitted a patch the new release 1.0.2 should be available in 1-2 days.
